// Region definitions for Footer display

export const PREF_IDS = {
    HOKKAIDO: 'hokkaido',
    AOMORI: 'aomori',
    IWATE: 'iwate',
    MIYAGI: 'miyagi',
    AKITA: 'akita',
    YAMAGATA: 'yamagata',
    FUKUSHIMA: 'fukushima',
    IBARAKI: 'ibaraki',
    TOCHIGI: 'tochigi',
    GUNMA: 'gunma',
    SAITAMA: 'saitama',
    CHIBA: 'chiba',
    TOKYO: 'tokyo',
    KANAGAWA: 'kanagawa',
    YAMANASHI: 'yamanashi',
    NAGANO: 'nagano',
    NIIGATA: 'niigata',
    TOYAMA: 'toyama',
    ISHIKAWA: 'ishikawa',
    FUKUI: 'fukui',
    GIFU: 'gifu',
    SHIZUOKA: 'shizuoka',
    AICHI: 'aichi',
    MIE: 'mie',
    SHIGA: 'shiga',
    KYOTO: 'kyoto',
    OSAKA: 'osaka',
    HYOGO: 'hyogo',
    NARA: 'nara',
    WAKAYAMA: 'wakayama',
    TOTTORI: 'tottori',
    SHIMANE: 'shimane',
    OKAYAMA: 'okayama',
    HIROSHIMA: 'hiroshima',
    YAMAGUCHI: 'yamaguchi',
    TOKUSHIMA: 'tokushima',
    KAGAWA: 'kagawa',
    EHIME: 'ehime',
    KOCHI: 'kochi',
    FUKUOKA: 'fukuoka',
    SAGA: 'saga',
    NAGASAKI: 'nagasaki',
    KUMAMOTO: 'kumamoto',
    OITA: 'oita',
    MIYAZAKI: 'miyazaki',
    KAGOSHIMA: 'kagoshima',
    OKINAWA: 'okinawa',
} as const;

export const REGULATIONS = [
    { id: PREF_IDS.HOKKAIDO, name: '北海道', prefs: [PREF_IDS.HOKKAIDO] },
    { id: 'tohoku', name: '東北', prefs: [PREF_IDS.AOMORI, PREF_IDS.IWATE, PREF_IDS.MIYAGI, PREF_IDS.AKITA, PREF_IDS.YAMAGATA, PREF_IDS.FUKUSHIMA] },
    { id: 'kanto', name: '関東', prefs: [PREF_IDS.IBARAKI, PREF_IDS.TOCHIGI, PREF_IDS.GUNMA, PREF_IDS.SAITAMA, PREF_IDS.CHIBA, PREF_IDS.TOKYO, PREF_IDS.KANAGAWA, PREF_IDS.YAMANASHI, PREF_IDS.NAGANO] },
    { id: 'hokuriku', name: '北陸', prefs: [PREF_IDS.NIIGATA, PREF_IDS.TOYAMA, PREF_IDS.ISHIKAWA, PREF_IDS.FUKUI] },
    { id: 'chubu', name: '中部', prefs: [PREF_IDS.GIFU, PREF_IDS.SHIZUOKA, PREF_IDS.AICHI, PREF_IDS.MIE] },
    { id: 'kinki', name: '近畿', prefs: [PREF_IDS.SHIGA, PREF_IDS.KYOTO, PREF_IDS.OSAKA, PREF_IDS.HYOGO, PREF_IDS.NARA, PREF_IDS.WAKAYAMA] },
    { id: 'chugoku', name: '中国', prefs: [PREF_IDS.TOTTORI, PREF_IDS.SHIMANE, PREF_IDS.OKAYAMA, PREF_IDS.HIROSHIMA, PREF_IDS.YAMAGUCHI] },
    { id: 'shikoku', name: '四国', prefs: [PREF_IDS.TOKUSHIMA, PREF_IDS.KAGAWA, PREF_IDS.EHIME, PREF_IDS.KOCHI] },
    { id: 'kyushu', name: '九州', prefs: [PREF_IDS.FUKUOKA, PREF_IDS.SAGA, PREF_IDS.NAGASAKI, PREF_IDS.KUMAMOTO, PREF_IDS.OITA, PREF_IDS.MIYAZAKI, PREF_IDS.KAGOSHIMA] },
    { id: PREF_IDS.OKINAWA, name: '沖縄', prefs: [PREF_IDS.OKINAWA] },
] as const;

export const PREFECTURES = [
    { id: PREF_IDS.HOKKAIDO, name: '北海道' },
    { id: PREF_IDS.AOMORI, name: '青森県' },
    { id: PREF_IDS.IWATE, name: '岩手県' },
    { id: PREF_IDS.MIYAGI, name: '宮城県' },
    { id: PREF_IDS.AKITA, name: '秋田県' },
    { id: PREF_IDS.YAMAGATA, name: '山形県' },
    { id: PREF_IDS.FUKUSHIMA, name: '福島県' },
    { id: PREF_IDS.IBARAKI, name: '茨城県' },
    { id: PREF_IDS.TOCHIGI, name: '栃木県' },
    { id: PREF_IDS.GUNMA, name: '群馬県' },
    { id: PREF_IDS.SAITAMA, name: '埼玉県' },
    { id: PREF_IDS.CHIBA, name: '千葉県' },
    { id: PREF_IDS.TOKYO, name: '東京都' },
    { id: PREF_IDS.KANAGAWA, name: '神奈川県' },
    { id: PREF_IDS.YAMANASHI, name: '山梨県' },
    { id: PREF_IDS.NAGANO, name: '長野県' },
    { id: PREF_IDS.NIIGATA, name: '新潟県' },
    { id: PREF_IDS.TOYAMA, name: '富山県' },
    { id: PREF_IDS.ISHIKAWA, name: '石川県' },
    { id: PREF_IDS.FUKUI, name: '福井県' },
    { id: PREF_IDS.GIFU, name: '岐阜県' },
    { id: PREF_IDS.SHIZUOKA, name: '静岡県' },
    { id: PREF_IDS.AICHI, name: '愛知県' },
    { id: PREF_IDS.MIE, name: '三重県' },
    { id: PREF_IDS.SHIGA, name: '滋賀県' },
    { id: PREF_IDS.KYOTO, name: '京都府' },
    { id: PREF_IDS.OSAKA, name: '大阪府' },
    { id: PREF_IDS.HYOGO, name: '兵庫県' },
    { id: PREF_IDS.NARA, name: '奈良県' },
    { id: PREF_IDS.WAKAYAMA, name: '和歌山県' },
    { id: PREF_IDS.TOTTORI, name: '鳥取県' },
    { id: PREF_IDS.SHIMANE, name: '島根県' },
    { id: PREF_IDS.OKAYAMA, name: '岡山県' },
    { id: PREF_IDS.HIROSHIMA, name: '広島県' },
    { id: PREF_IDS.YAMAGUCHI, name: '山口県' },
    { id: PREF_IDS.TOKUSHIMA, name: '徳島県' },
    { id: PREF_IDS.KAGAWA, name: '香川県' },
    { id: PREF_IDS.EHIME, name: '愛媛県' },
    { id: PREF_IDS.KOCHI, name: '高知県' },
    { id: PREF_IDS.FUKUOKA, name: '福岡県' },
    { id: PREF_IDS.SAGA, name: '佐賀県' },
    { id: PREF_IDS.NAGASAKI, name: '長崎県' },
    { id: PREF_IDS.KUMAMOTO, name: '熊本県' },
    { id: PREF_IDS.OITA, name: '大分県' },
    { id: PREF_IDS.MIYAZAKI, name: '宮崎県' },
    { id: PREF_IDS.KAGOSHIMA, name: '鹿児島県' },
    { id: PREF_IDS.OKINAWA, name: '沖縄県' },
] as const;

export const SCENES = [
    { slug: 'date', label: 'デート', icon: 'Heart' },
    { slug: 'solo', label: '一人メシ', icon: 'User' },
    { slug: 'business', label: '接待・会食', icon: 'Briefcase' },
    { slug: 'family', label: '家族・子供', icon: 'Users' },
    { slug: 'group', label: '飲み会・宴会', icon: 'Beer' },
] as const;

export const getPrefectureName = (slug: string) => {
    return PREFECTURES.find((p) => p.id === slug)?.name || slug;
};

export const CITIES = {
    // === HOKKAIDO ===
    [PREF_IDS.HOKKAIDO]: [
        { id: "sapporo", name: "札幌市" },
        { id: "hakodate", name: "函館市" },
        { id: "otaru", name: "小樽市" },
        { id: "asahikawa", name: "旭川市" },
        { id: "muroran", name: "室蘭市" },
        { id: "kushiro", name: "釧路市" },
        { id: "obihiro", name: "帯広市" },
        { id: "kitami", name: "北見市" },
        { id: "yubari", name: "夕張市" },
        { id: "iwamizawa", name: "岩見沢市" },
        { id: "abashiri", name: "網走市" },
        { id: "rumoi", name: "留萌市" },
        { id: "tomakomai", name: "苫小牧市" },
        { id: "wakkanai", name: "稚内市" },
        { id: "bibai", name: "美唄市" },
        { id: "ashibetsu", name: "芦別市" },
        { id: "ebetsu", name: "江別市" },
        { id: "akabira", name: "赤平市" },
        { id: "mombetsu", name: "紋別市" },
        { id: "shibetsu", name: "士別市" },
        { id: "nayoro", name: "名寄市" },
        { id: "mikasa", name: "三笠市" },
        { id: "nemuro", name: "根室市" },
        { id: "chitose", name: "千歳市" },
        { id: "takikawa", name: "滝川市" },
        { id: "sunagawa", name: "砂川市" },
        { id: "utashinai", name: "歌志内市" },
        { id: "fukagawa", name: "深川市" },
        { id: "furano", name: "富良野市" },
        { id: "noboribetsu", name: "登別市" },
        { id: "eniwa", name: "恵庭市" },
        { id: "date", name: "伊達市" },
        { id: "kitahiroshima", name: "北広島市" },
        { id: "ishikari", name: "石狩市" },
        { id: "hokuto", name: "北斗市" }
    ],
    // === TOHOKU ===
    [PREF_IDS.AOMORI]: [
        { id: "aomori", name: "青森市" },
        { id: "hirosaki", name: "弘前市" },
        { id: "hachinohe", name: "八戸市" },
        { id: "kuroishi", name: "黒石市" },
        { id: "goshogawara", name: "五所川原市" },
        { id: "towada", name: "十和田市" },
        { id: "misawa", name: "三沢市" },
        { id: "mutsu", name: "むつ市" },
        { id: "tsugaru", name: "つがる市" },
        { id: "hirakawa", name: "平川市" }
    ],
    [PREF_IDS.IWATE]: [
        { id: "morioka", name: "盛岡市" },
        { id: "miyako", name: "宮古市" },
        { id: "ofunato", name: "大船渡市" },
        { id: "hanamaki", name: "花巻市" },
        { id: "kitakami", name: "北上市" },
        { id: "kuji", name: "久慈市" },
        { id: "tono", name: "遠野市" },
        { id: "ichinoseki", name: "一関市" },
        { id: "rikuzentakata", name: "陸前高田市" },
        { id: "kamaishi", name: "釜石市" },
        { id: "ninohe", name: "二戸市" },
        { id: "hachimantai", name: "八幡平市" },
        { id: "oshu", name: "奥州市" },
        { id: "takizawa", name: "滝沢市" }
    ],
    [PREF_IDS.MIYAGI]: [
        { id: "sendai", name: "仙台市" },
        { id: "ishinomaki", name: "石巻市" },
        { id: "shiogama", name: "塩竈市" },
        { id: "kesennuma", name: "気仙沼市" },
        { id: "shiroishi", name: "白石市" },
        { id: "natori", name: "名取市" },
        { id: "kakuda", name: "角田市" },
        { id: "tagajo", name: "多賀城市" },
        { id: "iwanuma", name: "岩沼市" },
        { id: "tome", name: "登米市" },
        { id: "kurihara", name: "栗原市" },
        { id: "higashimatsushima", name: "東松島市" },
        { id: "osaki", name: "大崎市" },
        { id: "tomiya", name: "富谷市" }
    ],
    [PREF_IDS.AKITA]: [
        { id: "akita", name: "秋田市" },
        { id: "noshiro", name: "能代市" },
        { id: "yokote", name: "横手市" },
        { id: "odate", name: "大館市" },
        { id: "oga", name: "男鹿市" },
        { id: "yuzawa", name: "湯沢市" },
        { id: "kazuno", name: "鹿角市" },
        { id: "yurihonjo", name: "由利本荘市" },
        { id: "katagami", name: "潟上市" },
        { id: "daisen", name: "大仙市" },
        { id: "kitaakita", name: "北秋田市" },
        { id: "nikaho", name: "にかほ市" },
        { id: "semboku", name: "仙北市" }
    ],
    [PREF_IDS.YAMAGATA]: [
        { id: "yamagata", name: "山形市" },
        { id: "yonezawa", name: "米沢市" },
        { id: "tsuruoka", name: "鶴岡市" },
        { id: "sakata", name: "酒田市" },
        { id: "shinjo", name: "新庄市" },
        { id: "sagae", name: "寒河江市" },
        { id: "kaminoyama", name: "上山市" },
        { id: "murayama", name: "村山市" },
        { id: "nagai", name: "長井市" },
        { id: "tendo", name: "天童市" },
        { id: "higashine", name: "東根市" },
        { id: "obanazawa", name: "尾花沢市" },
        { id: "nanyo", name: "南陽市" }
    ],
    [PREF_IDS.FUKUSHIMA]: [
        { id: "fukushima", name: "福島市" },
        { id: "aizuwakamatsu", name: "会津若松市" },
        { id: "koriyama", name: "郡山市" },
        { id: "iwaki", name: "いわき市" },
        { id: "shirakawa", name: "白河市" },
        { id: "sukagawa", name: "須賀川市" },
        { id: "kitakata", name: "喜多方市" },
        { id: "soma", name: "相馬市" },
        { id: "nihonmatsu", name: "二本松市" },
        { id: "tamura", name: "田村市" },
        { id: "minamisoma", name: "南相馬市" },
        { id: "date", name: "伊達市" },
        { id: "motomiya", name: "本宮市" }
    ],
    // === KANTO (Partial) Placeholders for next steps ===
    [PREF_IDS.IBARAKI]: [
        { id: "mito", name: "水戸市" },
        { id: "hitachi", name: "日立市" },
        { id: "tsuchiura", name: "土浦市" },
        { id: "koga", name: "古河市" },
        { id: "ishioka", name: "石岡市" },
        { id: "yuki", name: "結城市" },
        { id: "ryugasaki", name: "龍ケ崎市" },
        { id: "shimotsuma", name: "下妻市" },
        { id: "joso", name: "常総市" },
        { id: "hitachiota", name: "常陸太田市" },
        { id: "takahagi", name: "高萩市" },
        { id: "kitaibaraki", name: "北茨城市" },
        { id: "kasama", name: "笠間市" },
        { id: "toride", name: "取手市" },
        { id: "ushiku", name: "牛久市" },
        { id: "tsukuba", name: "つくば市" },
        { id: "hitachinaka", name: "ひたちなか市" },
        { id: "kashima", name: "鹿嶋市" },
        { id: "itako", name: "潮来市" },
        { id: "moriya", name: "守谷市" },
        { id: "hitachiomiya", name: "常陸大宮市" },
        { id: "naka", name: "那珂市" },
        { id: "chikusei", name: "筑西市" },
        { id: "bando", name: "坂東市" },
        { id: "inashiki", name: "稲敷市" },
        { id: "kasumigaura", name: "かすみがうら市" },
        { id: "sakuragawa", name: "桜川市" },
        { id: "kamisu", name: "神栖市" },
        { id: "namegata", name: "行方市" },
        { id: "hokota", name: "鉾田市" },
        { id: "tsukubamirai", name: "つくばみらい市" },
        { id: "omitama", name: "小美玉市" }
    ],
    [PREF_IDS.TOCHIGI]: [
        { id: "utsunomiya", name: "宇都宮市" },
        { id: "ashikaga", name: "足利市" },
        { id: "tochigi", name: "栃木市" },
        { id: "sano", name: "佐野市" },
        { id: "kanuma", name: "鹿沼市" },
        { id: "nikko", name: "日光市" },
        { id: "oyama", name: "小山市" },
        { id: "moka", name: "真岡市" },
        { id: "ohtawara", name: "大田原市" },
        { id: "yaita", name: "矢板市" },
        { id: "nasushiobara", name: "那須塩原市" },
        { id: "sakura", name: "さくら市" },
        { id: "nasukarasuyama", name: "那須烏山市" },
        { id: "shimotsuke", name: "下野市" }
    ],
    [PREF_IDS.GUNMA]: [
        { id: "maebashi", name: "前橋市" },
        { id: "takasaki", name: "高崎市" },
        { id: "kiryu", name: "桐生市" },
        { id: "isesaki", name: "伊勢崎市" },
        { id: "ota", name: "太田市" },
        { id: "numata", name: "沼田市" },
        { id: "tatebayashi", name: "館林市" },
        { id: "shibukawa", name: "渋川市" },
        { id: "fujioka", name: "藤岡市" },
        { id: "tomioka", name: "富岡市" },
        { id: "annaka", name: "安中市" },
        { id: "midori", name: "みどり市" }
    ],
    [PREF_IDS.SAITAMA]: [
        { id: "saitama", name: "さいたま市" },
        { id: "kawagoe", name: "川越市" },
        { id: "kumagaya", name: "熊谷市" },
        { id: "kawaguchi", name: "川口市" },
        { id: "gyoda", name: "行田市" },
        { id: "chichibu", name: "秩父市" },
        { id: "tokorozawa", name: "所沢市" },
        { id: "hanno", name: "飯能市" },
        { id: "kazo", name: "加須市" },
        { id: "honjo", name: "本庄市" },
        { id: "higashimatsuyama", name: "東松山市" },
        { id: "kasukabe", name: "春日部市" },
        { id: "sayama", name: "狭山市" },
        { id: "hanyu", name: "羽生市" },
        { id: "konosu", name: "鴻巣市" },
        { id: "fukaya", name: "深谷市" },
        { id: "ageo", name: "上尾市" },
        { id: "soka", name: "草加市" },
        { id: "koshigaya", name: "越谷市" },
        { id: "warabi", name: "蕨市" },
        { id: "toda", name: "戸田市" },
        { id: "iruma", name: "入間市" },
        { id: "asaka", name: "朝霞市" },
        { id: "shiki", name: "志木市" },
        { id: "wako", name: "和光市" },
        { id: "niiza", name: "新座市" },
        { id: "okegawa", name: "桶川市" },
        { id: "kuki", name: "久喜市" },
        { id: "kitamoto", name: "北本市" },
        { id: "yashio", name: "八潮市" },
        { id: "fujimi", name: "富士見市" },
        { id: "misato", name: "三郷市" },
        { id: "hasuda", name: "蓮田市" },
        { id: "sakado", name: "坂戸市" },
        { id: "satte", name: "幸手市" },
        { id: "tsurugashima", name: "鶴ヶ島市" },
        { id: "hidaka", name: "日高市" },
        { id: "yoshikawa", name: "吉川市" },
        { id: "fujimino", name: "ふじみ野市" },
        { id: "shiraoka", name: "白岡市" }
    ],
    [PREF_IDS.CHIBA]: [
        { id: "chiba", name: "千葉市" },
        { id: "choshi", name: "銚子市" },
        { id: "ichikawa", name: "市川市" },
        { id: "funabashi", name: "船橋市" },
        { id: "tateyama", name: "館山市" },
        { id: "kisarazu", name: "木更津市" },
        { id: "matsudo", name: "松戸市" },
        { id: "noda", name: "野田市" },
        { id: "mobara", name: "茂原市" },
        { id: "narita", name: "成田市" },
        { id: "sakura", name: "佐倉市" },
        { id: "togane", name: "東金市" },
        { id: "asahi", name: "旭市" },
        { id: "narashino", name: "習志野市" },
        { id: "kashiwa", name: "柏市" },
        { id: "katsuura", name: "勝浦市" },
        { id: "ichihara", name: "市原市" },
        { id: "nagareyama", name: "流山市" },
        { id: "yachiyo", name: "八千代市" },
        { id: "abiko", name: "我孫子市" },
        { id: "kamogawa", name: "鴨川市" },
        { id: "kamagaya", name: "鎌ケ谷市" },
        { id: "kimitsu", name: "君津市" },
        { id: "futtsu", name: "富津市" },
        { id: "urayasu", name: "浦安市" },
        { id: "yotsukaido", name: "四街道市" },
        { id: "sodegaura", name: "袖ケ浦市" },
        { id: "yachimata", name: "八街市" },
        { id: "inzai", name: "印西市" },
        { id: "shiroi", name: "白井市" },
        { id: "tomisato", name: "富里市" },
        { id: "minamiboso", name: "南房総市" },
        { id: "sosa", name: "匝瑳市" },
        { id: "katori", name: "香取市" },
        { id: "sanmu", name: "山武市" },
        { id: "isumi", name: "いすみ市" },
        { id: "oamishirasato", name: "大網白里市" }
    ],
    [PREF_IDS.TOKYO]: [
        // 23 Wards
        { id: "chiyoda-ku", name: "千代田区" },
        { id: "chuo-ku", name: "中央区" },
        { id: "minato-ku", name: "港区" },
        { id: "shinjuku-ku", name: "新宿区" },
        { id: "bunkyo-ku", name: "文京区" },
        { id: "taito-ku", name: "台東区" },
        { id: "sumida-ku", name: "墨田区" },
        { id: "koto-ku", name: "江東区" },
        { id: "shinagawa-ku", name: "品川区" },
        { id: "meguro-ku", name: "目黒区" },
        { id: "ota-ku", name: "大田区" },
        { id: "setagaya-ku", name: "世田谷区" },
        { id: "shibuya-ku", name: "渋谷区" },
        { id: "nakano-ku", name: "中野区" },
        { id: "suginami-ku", name: "杉並区" },
        { id: "toshima-ku", name: "豊島区" },
        { id: "kita-ku", name: "北区" },
        { id: "arakawa-ku", name: "荒川区" },
        { id: "itabashi-ku", name: "板橋区" },
        { id: "nerima-ku", name: "練馬区" },
        { id: "adachi-ku", name: "足立区" },
        { id: "katsushika-ku", name: "葛飾区" },
        { id: "edogawa-ku", name: "江戸川区" },
        // Cities
        { id: "hachioji", name: "八王子市" },
        { id: "tachikawa", name: "立川市" },
        { id: "musashino", name: "武蔵野市" },
        { id: "mitaka", name: "三鷹市" },
        { id: "ome", name: "青梅市" },
        { id: "fuchu", name: "府中市" },
        { id: "akishima", name: "昭島市" },
        { id: "chofu", name: "調布市" },
        { id: "machida", name: "町田市" },
        { id: "koganei", name: "小金井市" },
        { id: "kodaira", name: "小平市" },
        { id: "hino", name: "日野市" },
        { id: "higashimurayama", name: "東村山市" },
        { id: "kokubunji", name: "国分寺市" },
        { id: "kunitachi", name: "国立市" },
        { id: "fussa", name: "福生市" },
        { id: "komae", name: "狛江市" },
        { id: "higashiyamato", name: "東大和市" },
        { id: "kiyose", name: "清瀬市" },
        { id: "higashikurume", name: "東久留米市" },
        { id: "musashimurayama", name: "武蔵村山市" },
        { id: "tama", name: "多摩市" },
        { id: "inagi", name: "稲城市" },
        { id: "hamura", name: "羽村市" },
        { id: "akiruno", name: "あきる野市" },
        { id: "nishitokyo", name: "西東京市" }
    ],
    [PREF_IDS.KANAGAWA]: [
        { id: "yokohama", name: "横浜市" },
        { id: "kawasaki", name: "川崎市" },
        { id: "sagamihara", name: "相模原市" },
        { id: "yokosuka", name: "横須賀市" },
        { id: "hiratsuka", name: "平塚市" },
        { id: "kamakura", name: "鎌倉市" },
        { id: "fujisawa", name: "藤沢市" },
        { id: "odawara", name: "小田原市" },
        { id: "chigasaki", name: "茅ヶ崎市" },
        { id: "zushi", name: "逗子市" },
        { id: "miura", name: "三浦市" },
        { id: "hadano", name: "秦野市" },
        { id: "atsugi", name: "厚木市" },
        { id: "yamato", name: "大和市" },
        { id: "isehara", name: "伊勢原市" },
        { id: "ebina", name: "海老名市" },
        { id: "zama", name: "座間市" },
        { id: "minamiashigara", name: "南足柄市" },
        { id: "ayase", name: "綾瀬市" }
    ],
    [PREF_IDS.YAMANASHI]: [
        { id: "kofu", name: "甲府市" },
        { id: "fujiyoshida", name: "富士吉田市" },
        { id: "tsuru", name: "都留市" },
        { id: "yamanashi", name: "山梨市" },
        { id: "otsuki", name: "大月市" },
        { id: "nirasaki", name: "韮崎市" },
        { id: "minamialps", name: "南アルプス市" },
        { id: "hokuto", name: "北杜市" },
        { id: "kai", name: "甲斐市" },
        { id: "fuefuki", name: "笛吹市" },
        { id: "uenohara", name: "上野原市" },
        { id: "koshu", name: "甲州市" },
        { id: "chuo", name: "中央市" }
    ],
    [PREF_IDS.NAGANO]: [
        { id: "nagano", name: "長野市" },
        { id: "matsumoto", name: "松本市" },
        { id: "ueda", name: "上田市" },
        { id: "okaya", name: "岡谷市" },
        { id: "iida", name: "飯田市" },
        { id: "suwa", name: "諏訪市" },
        { id: "suzaka", name: "須坂市" },
        { id: "komoro", name: "小諸市" },
        { id: "ina", name: "伊那市" },
        { id: "komagane", name: "駒ヶ根市" },
        { id: "nakano", name: "中野市" },
        { id: "omachi", name: "大町市" },
        { id: "iiyama", name: "飯山市" },
        { id: "chino", name: "茅野市" },
        { id: "shiojiri", name: "塩尻市" },
        { id: "saku", name: "佐久市" },
        { id: "chikuma", name: "千曲市" },
        { id: "tomi", name: "東御市" },
        { id: "azumino", name: "安曇野市" }
    ],
    // ... Rest will be filled by subsequent Replace calls to avoid truncation
    [PREF_IDS.NIIGATA]: [
        { id: "niigata", name: "新潟市" },
        { id: "nagaoka", name: "長岡市" },
        { id: "sanjo", name: "三条市" },
        { id: "kashiwazaki", name: "柏崎市" },
        { id: "shibata", name: "新発田市" },
        { id: "ojiya", name: "小千谷市" },
        { id: "kamo", name: "加茂市" },
        { id: "tokamachi", name: "十日町市" },
        { id: "mitsuke", name: "見附市" },
        { id: "murakami", name: "村上市" },
        { id: "tsubame", name: "燕市" },
        { id: "itoigawa", name: "糸魚川市" },
        { id: "myoko", name: "妙高市" },
        { id: "gosen", name: "五泉市" },
        { id: "joetsu", name: "上越市" },
        { id: "agano", name: "阿賀野市" },
        { id: "sado", name: "佐渡市" },
        { id: "uonuma", name: "魚沼市" },
        { id: "minamiuonuma", name: "南魚沼市" },
        { id: "tainai", name: "胎内市" }
    ],
    [PREF_IDS.TOYAMA]: [
        { id: "toyama", name: "富山市" },
        { id: "takaoka", name: "高岡市" },
        { id: "uozu", name: "魚津市" },
        { id: "imi", name: "氷見市" },
        { id: "namerikawa", name: "滑川市" },
        { id: "kurobe", name: "黒部市" },
        { id: "tonami", name: "砺波市" },
        { id: "oyabe", name: "小矢部市" },
        { id: "nanto", name: "南砺市" },
        { id: "imizu", name: "射水市" }
    ],
    [PREF_IDS.ISHIKAWA]: [
        { id: "kanazawa", name: "金沢市" },
        { id: "nanao", name: "七尾市" },
        { id: "komatsu", name: "小松市" },
        { id: "wajima", name: "輪島市" },
        { id: "suzu", name: "珠洲市" },
        { id: "kaga", name: "加賀市" },
        { id: "hakui", name: "羽咋市" },
        { id: "kahoku", name: "かほく市" },
        { id: "hakusan", name: "白山市" },
        { id: "nomi", name: "能美市" },
        { id: "nonoichi", name: "野々市市" }
    ],
    [PREF_IDS.FUKUI]: [
        { id: "fukui", name: "福井市" },
        { id: "tsuruga", name: "敦賀市" },
        { id: "obama", name: "小浜市" },
        { id: "ono", name: "大野市" },
        { id: "katsuyama", name: "勝山市" },
        { id: "sabae", name: "鯖江市" },
        { id: "awara", name: "あわら市" },
        { id: "echizen", name: "越前市" },
        { id: "sakai", name: "坂井市" }
    ],
    [PREF_IDS.GIFU]: [
        { id: "gifu", name: "岐阜市" },
        { id: "ogaki", name: "大垣市" },
        { id: "takayama", name: "高山市" },
        { id: "tajimi", name: "多治見市" },
        { id: "seki", name: "関市" },
        { id: "nakatsugawa", name: "中津川市" },
        { id: "mino", name: "美濃市" },
        { id: "mizunami", name: "瑞浪市" },
        { id: "hashima", name: "羽島市" },
        { id: "ena", name: "恵那市" },
        { id: "minokamo", name: "美濃加茂市" },
        { id: "toki", name: "土岐市" },
        { id: "kakamigahara", name: "各務原市" },
        { id: "kani", name: "可児市" },
        { id: "yamagata", name: "山県市" },
        { id: "mizuho", name: "瑞穂市" },
        { id: "hida", name: "飛騨市" },
        { id: "motosu", name: "本巣市" },
        { id: "gujo", name: "郡上市" },
        { id: "gero", name: "下呂市" },
        { id: "kaizu", name: "海津市" }
    ],
    [PREF_IDS.SHIZUOKA]: [
        { id: "shizuoka", name: "静岡市" },
        { id: "hamamatsu", name: "浜松市" },
        { id: "numazu", name: "沼津市" },
        { id: "atami", name: "熱海市" },
        { id: "mishima", name: "三島市" },
        { id: "fujinomiya", name: "富士宮市" },
        { id: "ito", name: "伊東市" },
        { id: "shimada", name: "島田市" },
        { id: "fuji", name: "富士市" },
        { id: "iwata", name: "磐田市" },
        { id: "yaizu", name: "焼津市" },
        { id: "kakegawa", name: "掛川市" },
        { id: "fujieda", name: "藤枝市" },
        { id: "gotemba", name: "御殿場市" },
        { id: "fukuroi", name: "袋井市" },
        { id: "shimoda", name: "下田市" },
        { id: "susono", name: "裾野市" },
        { id: "kosai", name: "湖西市" },
        { id: "izu", name: "伊豆市" },
        { id: "omaezaki", name: "御前崎市" },
        { id: "kikugawa", name: "菊川市" },
        { id: "izunokuni", name: "伊豆の国市" },
        { id: "makinohara", name: "牧之原市" }
    ],
    [PREF_IDS.AICHI]: [
        { id: "nagoya", name: "名古屋市" },
        { id: "toyohashi", name: "豊橋市" },
        { id: "okazaki", name: "岡崎市" },
        { id: "ichinomiya", name: "一宮市" },
        { id: "seto", name: "瀬戸市" },
        { id: "handa", name: "半田市" },
        { id: "kasugai", name: "春日井市" },
        { id: "toyokawa", name: "豊川市" },
        { id: "tsushima", name: "津島市" },
        { id: "hekinan", name: "碧南市" },
        { id: "kariya", name: "刈谷市" },
        { id: "toyota", name: "豊田市" },
        { id: "anjo", name: "安城市" },
        { id: "nishio", name: "西尾市" },
        { id: "gamagori", name: "蒲郡市" },
        { id: "inuyama", name: "犬山市" },
        { id: "tokoname", name: "常滑市" },
        { id: "konan", name: "江南市" },
        { id: "komaki", name: "小牧市" },
        { id: "inazawa", name: "稲沢市" },
        { id: "shinshiro", name: "新城市" },
        { id: "tokai", name: "東海市" },
        { id: "obu", name: "大府市" },
        { id: "chita", name: "知多市" },
        { id: "chiryu", name: "知立市" },
        { id: "owariasahi", name: "尾張旭市" },
        { id: "takahama", name: "高浜市" },
        { id: "iwakura", name: "岩倉市" },
        { id: "toyoyake", name: "豊明市" },
        { id: "nisshin", name: "日進市" },
        { id: "tahara", name: "田原市" },
        { id: "aisai", name: "愛西市" },
        { id: "kiyosu", name: "清須市" },
        { id: "kitanagoya", name: "北名古屋市" },
        { id: "yatomi", name: "弥富市" },
        { id: "miyoshi", name: "みよし市" },
        { id: "ama", name: "あま市" },
        { id: "nagakute", name: "長久手市" }
    ],
    [PREF_IDS.MIE]: [
        { id: "tsu", name: "津市" },
        { id: "yokkaichi", name: "四日市市" },
        { id: "ise", name: "伊勢市" },
        { id: "matsusaka", name: "松阪市" },
        { id: "kuwana", name: "桑名市" },
        { id: "suzuka", name: "鈴鹿市" },
        { id: "nabari", name: "名張市" },
        { id: "owase", name: "尾鷲市" },
        { id: "kameyama", name: "亀山市" },
        { id: "toba", name: "鳥羽市" },
        { id: "kumano", name: "熊野市" },
        { id: "inabe", name: "いなべ市" },
        { id: "shima", name: "志摩市" },
        { id: "iga", name: "伊賀市" }
    ],
    [PREF_IDS.SHIGA]: [
        { id: "otsu", name: "大津市" },
        { id: "hikone", name: "彦根市" },
        { id: "nagahama", name: "長浜市" },
        { id: "omihachiman", name: "近江八幡市" },
        { id: "kusatsu", name: "草津市" },
        { id: "moriyama", name: "守山市" },
        { id: "ritto", name: "栗東市" },
        { id: "koka", name: "甲賀市" },
        { id: "yasu", name: "野洲市" },
        { id: "konan", name: "湖南市" },
        { id: "takashima", name: "高島市" },
        { id: "higashiomi", name: "東近江市" },
        { id: "maibara", name: "米原市" }
    ],
    [PREF_IDS.KYOTO]: [
        { id: "kyoto", name: "京都市" },
        { id: "fukuchiyama", name: "福知山市" },
        { id: "maizuru", name: "舞鶴市" },
        { id: "ayabe", name: "綾部市" },
        { id: "uji", name: "宇治市" },
        { id: "miyazu", name: "宮津市" },
        { id: "kameoka", name: "亀岡市" },
        { id: "joyo", name: "城陽市" },
        { id: "muko", name: "向日市" },
        { id: "nagaokakyo", name: "長岡京市" },
        { id: "yawata", name: "八幡市" },
        { id: "kyotanabe", name: "京田辺市" },
        { id: "kyotango", name: "京丹後市" },
        { id: "nantan", name: "南丹市" },
        { id: "kizugawa", name: "木津川市" }
    ],
    [PREF_IDS.OSAKA]: [
        { id: "osaka", name: "大阪市" },
        { id: "sakai", name: "堺市" },
        { id: "kishiwada", name: "岸和田市" },
        { id: "toyonaka", name: "豊中市" },
        { id: "ikeda", name: "池田市" },
        { id: "suita", name: "吹田市" },
        { id: "izumiotsu", name: "泉大津市" },
        { id: "takatsuki", name: "高槻市" },
        { id: "kaizuka", name: "貝塚市" },
        { id: "moriguchi", name: "守口市" },
        { id: "hirakata", name: "枚方市" },
        { id: "ibaraki", name: "茨木市" },
        { id: "yao", name: "八尾市" },
        { id: "izumisano", name: "泉佐野市" },
        { id: "tondabayashi", name: "富田林市" },
        { id: "neyagawa", name: "寝屋川市" },
        { id: "kawachinagano", name: "河内長野市" },
        { id: "matsubara", name: "松原市" },
        { id: "daito", name: "大東市" },
        { id: "izumi", name: "和泉市" },
        { id: "minoh", name: "箕面市" },
        { id: "kashiwara", name: "柏原市" },
        { id: "habikino", name: "羽曳野市" },
        { id: "kadoma", name: "門真市" },
        { id: "settsu", name: "摂津市" },
        { id: "takaishi", name: "高石市" },
        { id: "fujiidera", name: "藤井寺市" },
        { id: "higashiosaka", name: "東大阪市" },
        { id: "sennan", name: "泉南市" },
        { id: "shijonawate", name: "四條畷市" },
        { id: "katano", name: "交野市" },
        { id: "osakasayama", name: "大阪狭山市" },
        { id: "hannan", name: "阪南市" }
    ],
    [PREF_IDS.HYOGO]: [
        { id: "kobe", name: "神戸市" },
        { id: "himeji", name: "姫路市" },
        { id: "amagasaki", name: "尼崎市" },
        { id: "akashi", name: "明石市" },
        { id: "nishinomiya", name: "西宮市" },
        { id: "sumoto", name: "洲本市" },
        { id: "ashiya", name: "芦屋市" },
        { id: "itami", name: "伊丹市" },
        { id: "aioi", name: "相生市" },
        { id: "toyooka", name: "豊岡市" },
        { id: "kakogawa", name: "加古川市" },
        { id: "ako", name: "赤穂市" },
        { id: "nishiwaki", name: "西脇市" },
        { id: "takarazuka", name: "宝塚市" },
        { id: "miki", name: "三木市" },
        { id: "takasago", name: "高砂市" },
        { id: "kawanishi", name: "川西市" },
        { id: "ono", name: "小野市" },
        { id: "sanda", name: "三田市" },
        { id: "kasai", name: "加西市" },
        { id: "sasayama", name: "丹波篠山市" },
        { id: "yabu", name: "養父市" },
        { id: "tamba", name: "丹波市" },
        { id: "minamiawaji", name: "南あわじ市" },
        { id: "asago", name: "朝来市" },
        { id: "awaji", name: "淡路市" },
        { id: "shiso", name: "宍粟市" },
        { id: "kato", name: "加東市" },
        { id: "tatsuno", name: "たつの市" }
    ],
    [PREF_IDS.NARA]: [
        { id: "nara", name: "奈良市" },
        { id: "yamatotakada", name: "大和高田市" },
        { id: "yamatokoriyama", name: "大和郡山市" },
        { id: "tenri", name: "天理市" },
        { id: "kashihara", name: "橿原市" },
        { id: "sakurai", name: "桜井市" },
        { id: "gojo", name: "五條市" },
        { id: "gose", name: "御所市" },
        { id: "ikoma", name: "生駒市" },
        { id: "kashiba", name: "香芝市" },
        { id: "katsuragi", name: "葛城市" },
        { id: "uda", name: "宇陀市" }
    ],
    [PREF_IDS.WAKAYAMA]: [
        { id: "wakayama", name: "和歌山市" },
        { id: "kainan", name: "海南市" },
        { id: "hashimoto", name: "橋本市" },
        { id: "arida", name: "有田市" },
        { id: "gobo", name: "御坊市" },
        { id: "tanabe", name: "田辺市" },
        { id: "shingu", name: "新宮市" },
        { id: "kinokawa", name: "紀の川市" },
        { id: "iwade", name: "岩出市" }
    ],
    [PREF_IDS.TOTTORI]: [
        { id: "tottori", name: "鳥取市" },
        { id: "yonago", name: "米子市" },
        { id: "kurayoshi", name: "倉吉市" },
        { id: "sakaiminato", name: "境港市" }
    ],
    [PREF_IDS.SHIMANE]: [
        { id: "matsue", name: "松江市" },
        { id: "hamada", name: "浜田市" },
        { id: "izumo", name: "出雲市" },
        { id: "masuda", name: "益田市" },
        { id: "oda", name: "大田市" },
        { id: "yasugi", name: "安来市" },
        { id: "gotsu", name: "江津市" },
        { id: "unnan", name: "雲南市" }
    ],
    [PREF_IDS.OKAYAMA]: [
        { id: "okayama", name: "岡山市" },
        { id: "kurashiki", name: "倉敷市" },
        { id: "tsuyama", name: "津山市" },
        { id: "tamano", name: "玉野市" },
        { id: "kasaoka", name: "笠岡市" },
        { id: "ibara", name: "井原市" },
        { id: "soja", name: "総社市" },
        { id: "takahashi", name: "高梁市" },
        { id: "niimi", name: "新見市" },
        { id: "bizen", name: "備前市" },
        { id: "setouchi", name: "瀬戸内市" },
        { id: "akaiwa", name: "赤磐市" },
        { id: "maniwa", name: "真庭市" },
        { id: "mimasaka", name: "美作市" },
        { id: "asakuchi", name: "浅口市" }
    ],
    [PREF_IDS.HIROSHIMA]: [
        { id: "hiroshima", name: "広島市" },
        { id: "kure", name: "呉市" },
        { id: "takehara", name: "竹原市" },
        { id: "mihara", name: "三原市" },
        { id: "onomichi", name: "尾道市" },
        { id: "fukuyama", name: "福山市" },
        { id: "fuchu-shi", name: "府中市" }, // Hiroshima's Fuchu
        { id: "miyoshi", name: "三次市" },
        { id: "shobara", name: "庄原市" },
        { id: "otake", name: "大竹市" },
        { id: "higashihiroshima", name: "東広島市" },
        { id: "hatsukaichi", name: "廿日市市" },
        { id: "akitakata", name: "安芸高田市" },
        { id: "etajima", name: "江田島市" }
    ],
    [PREF_IDS.YAMAGUCHI]: [
        { id: "shimonoseki", name: "下関市" },
        { id: "ube", name: "宇部市" },
        { id: "yamaguchi", name: "山口市" },
        { id: "hagi", name: "萩市" },
        { id: "hofu", name: "防府市" },
        { id: "kudamatsu", name: "下松市" },
        { id: "iwakuni", name: "岩国市" },
        { id: "hikari", name: "光市" },
        { id: "nagato", name: "長門市" },
        { id: "yanai", name: "柳井市" },
        { id: "mine", name: "美祢市" },
        { id: "shunan", name: "周南市" },
        { id: "sanyoonoda", name: "山陽小野田市" }
    ],
    [PREF_IDS.TOKUSHIMA]: [
        { id: "tokushima", name: "徳島市" },
        { id: "naruto", name: "鳴門市" },
        { id: "komatsushima", name: "小松島市" },
        { id: "anan", name: "阿南市" },
        { id: "yoshinogawa", name: "吉野川市" },
        { id: "awa", name: "阿波市" },
        { id: "mima", name: "美馬市" },
        { id: "miyoshi", name: "三好市" }
    ],
    [PREF_IDS.KAGAWA]: [
        { id: "takamatsu", name: "高松市" },
        { id: "marugame", name: "丸亀市" },
        { id: "sakaide", name: "坂出市" },
        { id: "zentsuji", name: "善通寺市" },
        { id: "kanonji", name: "観音寺市" },
        { id: "sanuki", name: "さぬき市" },
        { id: "higashikagawa", name: "東かがわ市" },
        { id: "mitoyo", name: "三豊市" }
    ],
    [PREF_IDS.EHIME]: [
        { id: "matsuyama", name: "松山市" },
        { id: "imabari", name: "今治市" },
        { id: "uwajima", name: "宇和島市" },
        { id: "yawatahama", name: "八幡浜市" },
        { id: "niihama", name: "新居浜市" },
        { id: "saijo", name: "西条市" },
        { id: "ozu", name: "大洲市" },
        { id: "iyo", name: "伊予市" },
        { id: "shikokuchuo", name: "四国中央市" },
        { id: "seiyo", name: "西予市" },
        { id: "toon", name: "東温市" }
    ],
    [PREF_IDS.KOCHI]: [
        { id: "kochi", name: "高知市" },
        { id: "muroto", name: "室戸市" },
        { id: "aki", name: "安芸市" },
        { id: "nankoku", name: "南国市" },
        { id: "tosa", name: "土佐市" },
        { id: "susaki", name: "須崎市" },
        { id: "sukumo", name: "宿毛市" },
        { id: "tosashimizu", name: "土佐清水市" },
        { id: "shimanto", name: "四万十市" },
        { id: "kami", name: "香美市" },
        { id: "konan", name: "香南市" }
    ],
    [PREF_IDS.FUKUOKA]: [
        { id: "kitakyushu", name: "北九州市" },
        { id: "fukuoka", name: "福岡市" },
        { id: "omuta", name: "大牟田市" },
        { id: "kurume", name: "久留米市" },
        { id: "nogata", name: "直方市" },
        { id: "iizuka", name: "飯塚市" },
        { id: "tagawa", name: "田川市" },
        { id: "yanagawa", name: "柳川市" },
        { id: "yame", name: "八女市" },
        { id: "chikugo", name: "筑後市" },
        { id: "okawa", name: "大川市" },
        { id: "yukuhashi", name: "行橋市" },
        { id: "buzen", name: "豊前市" },
        { id: "nakama", name: "中間市" },
        { id: "ogori", name: "小郡市" },
        { id: "chikushino", name: "筑紫野市" },
        { id: "kasuga", name: "春日市" },
        { id: "onojo", name: "大野城市" },
        { id: "munakata", name: "宗像市" },
        { id: "dazaifu", name: "太宰府市" },
        { id: "koga", name: "古賀市" },
        { id: "fukutsu", name: "福津市" },
        { id: "ukiiha", name: "うきは市" },
        { id: "miyawaka", name: "宮若市" },
        { id: "kama", name: "嘉麻市" },
        { id: "asakura", name: "朝倉市" },
        { id: "miyama", name: "みやま市" },
        { id: "itoshima", name: "糸島市" },
        { id: "nakagawa", name: "那珂川市" }
    ],
    [PREF_IDS.SAGA]: [
        { id: "saga", name: "佐賀市" },
        { id: "karatsu", name: "唐津市" },
        { id: "tosu", name: "鳥栖市" },
        { id: "taku", name: "多久市" },
        { id: "imari", name: "伊万里市" },
        { id: "takeo", name: "武雄市" },
        { id: "kashima", name: "鹿島市" },
        { id: "ogi", name: "小城市" },
        { id: "ureshino", name: "嬉野市" },
        { id: "kanzaki", name: "神埼市" }
    ],
    [PREF_IDS.NAGASAKI]: [
        { id: "nagasaki", name: "長崎市" },
        { id: "sasebo", name: "佐世保市" },
        { id: "shimabara", name: "島原市" },
        { id: "isahaya", name: "諫早市" },
        { id: "omura", name: "大村市" },
        { id: "hirado", name: "平戸市" },
        { id: "matsuura", name: "松浦市" },
        { id: "tsushima", name: "対馬市" },
        { id: "iki", name: "壱岐市" },
        { id: "goto", name: "五島市" },
        { id: "saikai", name: "西海市" },
        { id: "unzen", name: "雲仙市" },
        { id: "minamishimabara", name: "南島原市" }
    ],
    [PREF_IDS.KUMAMOTO]: [
        { id: "kumamoto", name: "熊本市" },
        { id: "yatsushiro", name: "八代市" },
        { id: "hitoyoshi", name: "人吉市" },
        { id: "arao", name: "荒尾市" },
        { id: "minamata", name: "水俣市" },
        { id: "tamana", name: "玉名市" },
        { id: "yamaga", name: "山鹿市" },
        { id: "kikuchi", name: "菊池市" },
        { id: "uto", name: "宇土市" },
        { id: "kamiamakusa", name: "上天草市" },
        { id: "uki", name: "宇城市" },
        { id: "aso", name: "阿蘇市" },
        { id: "amakusa", name: "天草市" },
        { id: "koshi", name: "合志市" }
    ],
    [PREF_IDS.OITA]: [
        { id: "oita", name: "大分市" },
        { id: "beppu", name: "別府市" },
        { id: "nakatsu", name: "中津市" },
        { id: "hita", name: "日田市" },
        { id: "saiki", name: "佐伯市" },
        { id: "usuki", name: "臼杵市" },
        { id: "tsukumi", name: "津久見市" },
        { id: "taketa", name: "竹田市" },
        { id: "bungotakada", name: "豊後高田市" },
        { id: "kitsuki", name: "杵築市" },
        { id: "usa", name: "宇佐市" },
        { id: "bungoono", name: "豊後大野市" },
        { id: "yufu", name: "由布市" },
        { id: "kunisaki", name: "国東市" }
    ],
    [PREF_IDS.MIYAZAKI]: [
        { id: "miyazaki", name: "宮崎市" },
        { id: "miyakonojo", name: "都城市" },
        { id: "nobeoka", name: "延岡市" },
        { id: "nichinan", name: "日南市" },
        { id: "kobayashi", name: "小林市" },
        { id: "hyuga", name: "日向市" },
        { id: "kushima", name: "串間市" },
        { id: "saito", name: "西都市" },
        { id: "ebino", name: "えびの市" }
    ],
    [PREF_IDS.KAGOSHIMA]: [
        { id: "kagoshima", name: "鹿児島市" },
        { id: "kanoya", name: "鹿屋市" },
        { id: "makurazaki", name: "枕崎市" },
        { id: "akune", name: "阿久根市" },
        { id: "izumi", name: "出水市" },
        { id: "ibusuki", name: "指宿市" },
        { id: "nishinoomote", name: "西之表市" },
        { id: "tarumizu", name: "垂水市" },
        { id: "satsumasendai", name: "薩摩川内市" },
        { id: "hioki", name: "日置市" },
        { id: "soo", name: "曽於市" },
        { id: "kirishima", name: "霧島市" },
        { id: "ichikikushikino", name: "いちき串木野市" },
        { id: "minamisatsuma", name: "南さつま市" },
        { id: "shibushi", name: "志布志市" },
        { id: "amami", name: "奄美市" },
        { id: "minamikyushu", name: "南九州市" },
        { id: "isa", name: "伊佐市" },
        { id: "aira", name: "姶良市" }
    ],
    [PREF_IDS.OKINAWA]: [
        { id: "naha", name: "那覇市" },
        { id: "ginowan", name: "宜野湾市" },
        { id: "ishigaki", name: "石垣市" },
        { id: "urasoe", name: "浦添市" },
        { id: "nago", name: "名護市" },
        { id: "itoman", name: "糸満市" },
        { id: "okinawa", name: "沖縄市" },
        { id: "tomigusuku", name: "豊見城市" },
        { id: "uruma", name: "うるま市" },
        { id: "miyakojima", name: "宮古島市" },
        { id: "nanjo", name: "南城市" }
    ]
};

/**
 * Validates if the prefecture and city combination is valid.
 * Uses .id for both checks.
 */
export function isValidArea(prefecture: string, city?: string): boolean {
    const prefExists = PREFECTURES.some(p => p.id === prefecture);
    if (!prefExists) return false;
    if (!city) return true;

    // @ts-ignore
    const cities = CITIES[prefecture];
    if (!cities) return false;

    return cities.some((c: any) => c.id === city);
}


/**
 * Validates if the scene slug is valid.
 */
export function isValidScene(scene: string): boolean {
    return SCENES.some(s => s.slug === scene);
}

/**
 * Returns the Japanese name for a city ID.
 */
export function getCityName(prefecture: string, city: string): string {
    // @ts-ignore
    const cities = CITIES[prefecture];
    if (!cities) return city;
    const target = cities.find((c: any) => c.id === city);
    return target ? target.name : city;
}

/**
 * Returns the Japanese label for a scene ID (slug).
 */
export function getSceneName(scene: string): string {
    const target = SCENES.find(s => s.slug === scene);
    return target ? target.label : scene;
}
